name: Package

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential pkg-config libtool libtinyxml2-dev libusb-1.0-0-dev libpthread-stubs0-dev libpulse-dev libasound2-dev

      - name: Configure LEDSpicer
        run: |
          sudo sh autogen.sh
          ./configure --enable-ultimateio --enable-ledwiz32 --enable-pacdrive --enable-alsaaudio

      - name: Compile LEDSpicer
        run: |
          make clean
          make -j5
          
      - name: check packages and move locally
        run: mkdir pkg; sudo find /tmp/project -name '*.deb' -exec mv {} pkg \;
        
      - name: Upload the artifacts
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'pkg/*.deb'
